# Generated by Django 3.1.5 on 2021-01-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0009_auto_20210125_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowsPerPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowsper', models.IntegerField(default=2)),
            ],
        ),
    ]
