# Generated by Django 3.1.5 on 2021-01-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0010_rowsperpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RowsPerPage',
        ),
        migrations.AlterField(
            model_name='vendorbasic',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='vendor_management.VendorTag'),
        ),
        migrations.AlterField(
            model_name='vendorbasic',
            name='trade',
            field=models.ManyToManyField(blank=True, null=True, to='vendor_management.VendorTrade'),
        ),
    ]
