# Generated by Django 3.1.5 on 2021-01-27 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_basic', '0007_auto_20210119_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessunit',
            old_name='bussname',
            new_name='name',
        ),
    ]
