# Generated by Django 3.1.5 on 2021-01-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_basic', '0011_contractbasic_contract_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractbasic',
            name='contract_items',
        ),
        migrations.RemoveField(
            model_name='contractbasic',
            name='contract_rates',
        ),
        migrations.RemoveField(
            model_name='contractbasic',
            name='initial_term',
        ),
        migrations.AlterField(
            model_name='contractbasic',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='contract_basic.Tags'),
        ),
    ]
